language: node_js
node_js:
- '11'
addons:
  ssh_known_hosts:
  - "$REMOTE_HOST"
  - "$REMOTE_HOST_IP"
after_success:
- chmod +x ".travis/public-deploy.sh"
- ".travis/public-deploy.sh"
before_install:
- openssl aes-256-cbc -K $encrypted_8c5969a1f9bc_key -iv $encrypted_8c5969a1f9bc_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
